import { createContext, ReactNode, useMemo, useState } from 'react';

import {
    EColumnType,
    EPositionInRow,
    ITableColumnConfig,
    ITableInjectableColumnConfig,
    TColumnId,
} from '@/components/Table/Table.models';

const rowCountColumnConfig: ITableInjectableColumnConfig = {
    columnId: 'rowCount',
    label: 'Nr',
    dataAccessor: 'rowCount',
    columnDataType: EColumnType.Nr,
    isSortable: false,
    isAutoGenerated: true,
    positionInRow: 0,
};

const TableSettingsContext = createContext<{
    // Data:
    columnConfigList: ITableColumnConfig[];
    autoGenColumnConfigList: ITableColumnConfig[];
    fullColumnConfigList: ITableColumnConfig[];
    isRowCountEnabled: boolean;
    // Functions:
    setColumnConfigList: (newColumnConfigList: ITableColumnConfig[]) => void;
    setIsRowCountEnabled: (isRowCountEnabled: boolean) => void;
}>({
    // Data:
    columnConfigList: [],
    autoGenColumnConfigList: [],
    fullColumnConfigList: [],
    isRowCountEnabled: true,
    // Functions:
    setColumnConfigList: (newColumnConfigList) => null,
    setIsRowCountEnabled: (isRowCountEnabled) => null,
});

const TableSettingsProvider = ({
    initColumnConfigList = [],
    initIsRowCountEnabled = true,
    children,
}: {
    initColumnConfigList: ITableColumnConfig[];
    initIsRowCountEnabled: boolean;
    children: ReactNode;
}) => {
    const [columnConfigList, setColumnConfigList] =
        useState<ITableColumnConfig[]>(initColumnConfigList);

    const [isRowCountEnabled, setIsRowCountEnabled] = useState<boolean>(initIsRowCountEnabled);

    const injectedColumnConfigList: ITableInjectableColumnConfig[] = useMemo(() => {
        const configList = [] as ITableInjectableColumnConfig[];

        if (isRowCountEnabled) {
            configList.push(rowCountColumnConfig);
        }

        return configList;
    }, [isRowCountEnabled]);

    const fullColumnConfigList = useMemo(() => {
        const fullColumnConfigList = [...columnConfigList];

        injectedColumnConfigList.forEach((injectedColumnConfig) => {
            const { positionInRow } = injectedColumnConfig;

            if (positionInRow == EPositionInRow.First || positionInRow === 0) {
                fullColumnConfigList.unshift(injectedColumnConfig);
            } else if (!isNaN(positionInRow as number) && positionInRow > 0) {
                fullColumnConfigList.splice(positionInRow as number, 0, injectedColumnConfig);
            } else {
                fullColumnConfigList.push(injectedColumnConfig);
            }
        });

        return fullColumnConfigList;
    }, [injectedColumnConfigList, columnConfigList]);

    return (
        <TableSettingsContext.Provider
            value={{
                // Data:
                columnConfigList: columnConfigList,
                autoGenColumnConfigList: injectedColumnConfigList,
                fullColumnConfigList: fullColumnConfigList,
                isRowCountEnabled,
                // Functions:
                setColumnConfigList,
                setIsRowCountEnabled,
            }}
        >
            {children}
        </TableSettingsContext.Provider>
    );
};

export { TableSettingsContext, TableSettingsProvider, rowCountColumnConfig };
