import React, { useContext } from 'react';

import TableDataCell from '@/components/Table/components/TableBody/TableDataCell';
import TableInjectedDataCell from '@/components/Table/components/TableBody/TableInjectedDataCell';
import { TableColumnsContext } from '@/components/Table/state/TableColumns/TableColumnsContext';

const TableDataRow = ({
    dataItem,
    rowIndex,
}: {
    dataItem: Record<string, any>;
    rowIndex: number;
}) => {
    const { fullColumnConfigList } = useContext(TableColumnsContext);

    return (
        <tr>
            {fullColumnConfigList.map((columnConfig) => {
                const { columnId, isAutoGenerated } = columnConfig;

                if (isAutoGenerated) {
                    return (
                        <TableInjectedDataCell
                            key={`${columnConfig.columnId}-${rowIndex}`}
                            columnConfig={columnConfig}
                            rowIndex={rowIndex}
                        />
                    );
                }

                const dataField = dataItem[columnId];

                return (
                    <TableDataCell
                        key={`${rowIndex}_${dataField}`}
                        dataField={dataField}
                        columnConfig={columnConfig}
                    />
                );
            })}
        </tr>
    );
};

export default TableDataRow;
