import { IColumnCustomStylingDto, TColumnId } from '@/components/Table/models/column.models';
import {
    TCellContent,
    TCellData,
    TDataFieldAccessFn,
    TTableRowData,
} from '@/components/Table/models/data.models';
import { IColumnSortConfig } from '@/components/Table/models/sorting.models';

interface ITableColumnConfig {
    label: string;
    columnId: TColumnId;
    dataAccessor: string | TDataFieldAccessFn;
    renderFn?: ({
        cellData,
        columnId,
        rowData,
    }: {
        cellData: TCellData;
        columnId: TColumnId;
        rowData: TTableRowData;
    }) => TCellContent;
    onCellClick?: () => void;
    columnStyleConfig?: IColumnCustomStylingDto;
    isSortable?: boolean;
    isAutoGenerated?: boolean;
}

interface ITableConfigProps {
    columnConfigList: ITableColumnConfig[];
    defaultSorting?: IColumnSortConfig[];
    isTableSettingChangeable?: boolean;
    isMultiSortSettingsEnabled?: boolean;
}

interface ITableSettingsProps {
    isMultiSortEnabled?: boolean;
    isRowCountEnabled?: boolean;
    isSearchEnabled?: boolean;
}

export type { ITableColumnConfig, ITableSettingsProps, ITableConfigProps };
