import { ReactNode } from 'react';
import tableRow from '@/components/Table/components/TableRow';
import { string } from 'prop-types';

enum EColumnAlign {
    Left = 'left',
    Right = 'right',
    Center = 'center',
}

enum EColumnSize {
    Xs = 'extra-small',
    Sm = 'small',
    Mid = 'medium',
    Lg = 'large',
    Xl = 'extra-large',
}

enum EColumnType {
    Nr = 'nr',
    Number = 'number',
    Date = 'date',
    DateTime = 'datetime',
    String = 'string',
    Text = 'text',
    Unknown = 'unknown',
}

interface IColumnCustomStylingDto {
    align?: EColumnAlign;
    size?: EColumnSize;
}

interface ITableColumnConfig {
    columnDataType?: EColumnType; // For default type styling
    label: string;
    columnId: TColumnId;
    dataAccessor: TDataFieldAccessor;
    onCellClick?: () => void;
    renderData?: () => ReactNode;
    customStylingDto?: IColumnCustomStylingDto;
    isSortable?: boolean;
    isAutoGenerated?: boolean;
}

enum EPositionInRow {
    First = 'first',
    Last = 'last',
}

interface ITableInjectableColumnConfig extends ITableColumnConfig {
    positionInRow: number | EPositionInRow;
}

interface ITableDataItemDto<FieldType> {
    columnKey: string;
    cellData: FieldType;
}

interface ITableRowProps<DtoType> {
    columnConfigList: ITableColumnConfig[];
    dataItem: DtoType;
    rowIndex: number;
    onRowClick?: () => void;
    isRowCountEnabled: boolean;
}

interface ITableProps {
    columnConfigList: ITableColumnConfig[];
    rowData: object[];
    onRowClick?: () => void;
    isRowCountEnabled?: boolean;
}

type TDataFieldAccessFn = <T>(rowData: T) => string | number | null;
type TDataFieldAccessor = string | TDataFieldAccessFn;

type TColumnId = string;
type TTableRowData = Record<TColumnId, string | number | null>;
type TTableData = TTableRowData[];

export type {
    ITableColumnConfig,
    ITableDataItemDto,
    ITableProps,
    ITableRowProps,
    ITableInjectableColumnConfig,
    TDataFieldAccessor,
    TDataFieldAccessFn,
    TColumnId,
    TTableRowData,
    TTableData,
};
export { EColumnType, EColumnSize, EColumnAlign, EPositionInRow };
